name: Hello World
on:
  push:
    branches:
      - main
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-Test-CodeBuild-Runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
